info:
  component: Config Server
spring:
  profiles:
    active: composite
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      allowOverride: true
      server:
        composite:

server:
  port: 8800
management:
  context_path: /admin
